# Generated by Django 3.1.2 on 2020-10-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_city_population'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='photo',
            new_name='photo_day',
        ),
        migrations.AddField(
            model_name='city',
            name='photo_night',
            field=models.CharField(default='photo.jpg', max_length=250),
        ),
    ]
