# Generated by Django 3.1.2 on 2020-10-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201008_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No Title Provided', max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.CharField(default='images/default_profile.png', max_length=250),
        ),
    ]
